version: '3.9'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: devDB
    ports:
      - '3306:3306'
    volumes:
      - ./dev-database.sql:/docker-entrypoint-initdb.d/01.sql
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: devDB
    depends_on:
      - mysql
    
  question-book:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysqldata:
